import React from 'react';
import { SectionHeader, Card3D, Button } from '../components/UI';
import { Share2, TrendingUp, Monitor, Layout, FileText, Cpu, Mail, Target, Video, ShoppingBag, Phone, Download, Play } from 'lucide-react';
import { Link } from 'react-router-dom';

const allServices = [
  { 
    id: 'smm', 
    title: 'Social Media Marketing', 
    desc: 'Engage your audience with content strategies tailored for viral growth on Instagram, LinkedIn, and Twitter.',
    icon: Share2,
    features: ['Content Calendar', 'Community Management', 'Influencer Outreach']
  },
  { 
    id: 'ads', 
    title: 'AI-Driven Ads', 
    desc: 'PPC campaigns managed by AI algorithms that adjust bids and targeting in real-time for maximum ROAS.',
    icon: TrendingUp,
    features: ['Google & Meta Ads', 'A/B Testing Automation', 'Retargeting funnels']
  },
  { 
    id: 'web', 
    title: 'Web Dev + SEO', 
    desc: 'Blazing fast websites optimized for search engines using the latest React frameworks and 3D visuals.',
    icon: Monitor,
    features: ['Responsive Design', 'Technical SEO', 'Speed Optimization']
  },
  { 
    id: 'graphic', 
    title: 'Branding & Design', 
    desc: 'Futuristic visual identities. Logos, UI/UX, and brand assets that stand out in the digital noise.',
    icon: Layout,
    features: ['Logo Design', 'Brand Guidelines', 'Social Assets']
  },
  { 
    id: 'content', 
    title: 'Content Creation', 
    desc: 'High-quality blogs, videos, and copy generated by human creativity enhanced with AI tools.',
    icon: FileText,
    features: ['Blog Writing', 'Video Scripts', 'E-books']
  },
  { 
    id: 'auto', 
    title: 'Marketing Automation', 
    desc: 'Set up CRM flows, email sequences, and chatbots that nurture leads while you sleep.',
    icon: Cpu,
    features: ['Email Workflows', 'Chatbot Setup', 'CRM Integration']
  },
  { 
    id: 'lead', 
    title: 'Lead Generation', 
    desc: 'Systems designed solely to fill your pipeline with qualified appointments and inquiries.',
    icon: Target,
    features: ['Landing Pages', 'Lead Magnets', 'Cold Outreach']
  },
  { 
    id: 'ugc', 
    title: 'UGC Video Ads', 
    desc: 'Authentic user-generated content ads that drive higher engagement and trust on social platforms.',
    icon: Video,
    features: ['Viral Creative Hooks', 'Creator Network', 'Native Ad Formats']
  },
  { 
    id: 'ecom', 
    title: 'E-Commerce Growth', 
    desc: 'Scalable Shopify & WooCommerce solutions designed for maximum sales performance.',
    icon: ShoppingBag,
    features: ['Store Setup & Design', 'Conversion Optimization', 'Cart Recovery']
  }
];

export const Services: React.FC = () => {
  return (
    <>
      <section className="pt-10 pb-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <SectionHeader title="Future-Ready Marketing Services" subtitle="Our Expertise" />
          
          {/* Engaging Description & CTAs */}
          <div className="max-w-3xl mx-auto text-center -mt-10 mb-16 px-4 relative z-10">
            <p className="text-gray-300 text-lg mb-8 leading-relaxed">
              Unlock exponential growth with our full-spectrum digital ecosystem. We fuse data science with creative brilliance to build brands that lead the AI revolution and dominate the market.
            </p>
            <div className="flex flex-col sm:flex-row justify-center gap-4">
              <a href="tel:+15551234567" className="w-full sm:w-auto">
                <Button variant="primary" className="w-full">
                  <Phone className="w-4 h-4 mr-2" /> Quick Call
                </Button>
              </a>
              <Button variant="outline" className="w-full sm:w-auto">
                <Download className="w-4 h-4 mr-2" /> Download Brochure
              </Button>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {allServices.map((service) => (
              <Card3D key={service.id} className="flex flex-col h-full">
                <div className="w-20 h-20 rounded-2xl bg-white/5 border border-white/10 flex items-center justify-center mb-6 text-cyan-400 transition-all duration-300 group-hover:bg-cyan-500/10 group-hover:border-cyan-400/30 group-hover:shadow-lg group-hover:shadow-cyan-500/20">
                  <service.icon size={40} className="transform transition-all duration-300 group-hover:scale-110 group-hover:text-cyan-300" />
                </div>
                
                <h3 className="text-2xl font-display font-bold text-white mb-4">{service.title}</h3>
                {/* Added min-h-[4.5rem] to ensure consistent alignment of features below */}
                <p className="text-gray-400 mb-6 min-h-[4.5rem]">{service.desc}</p>
                
                <div className="space-y-3 mb-8 flex-grow">
                  {service.features.map((feature, idx) => (
                    <div key={idx} className="flex items-center gap-3 text-sm text-gray-300">
                      <div className="w-1.5 h-1.5 rounded-full bg-purple-500"></div>
                      {feature}
                    </div>
                  ))}
                </div>

                <Link to="/booking" className="mt-auto">
                  <Button variant="outline" className="w-full">Request Quote</Button>
                </Link>
              </Card3D>
            ))}
          </div>
        </div>
      </section>

      {/* Video Section */}
      <section className="py-24 relative overflow-hidden bg-[#020617]">
        {/* Background Decorative Elements */}
        <div className="absolute top-1/2 left-0 -translate-y-1/2 w-[500px] h-[500px] bg-indigo-600/10 rounded-full blur-[120px] pointer-events-none"></div>
        <div className="absolute top-1/2 right-0 -translate-y-1/2 w-[400px] h-[400px] bg-cyan-600/10 rounded-full blur-[100px] pointer-events-none"></div>

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
            {/* Text Content */}
            <div className="order-2 lg:order-1">
              <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full glass-panel border-cyan-500/30 mb-6">
                <Play className="w-3 h-3 text-cyan-400 fill-cyan-400" />
                <span className="text-xs font-semibold uppercase tracking-widest text-cyan-300">Featured Content</span>
              </div>
              
              <h2 className="text-4xl md:text-5xl font-display font-bold text-white mb-6 leading-tight">
                See Innovation <br />
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-blue-500">
                  In Action
                </span>
              </h2>
              
              <p className="text-gray-300 text-lg mb-8 leading-relaxed">
                Dive deep into our AI-driven strategies and witness how we revolutionize digital presence. Watch our latest case studies and insights on how we help brands scale effortlessly.
              </p>
              
              <a href="https://youtube.com" target="_blank" rel="noreferrer">
                <Button variant="primary" icon>Visit YouTube Channel</Button>
              </a>
            </div>

            {/* Video Container */}
            <div className="order-1 lg:order-2 relative group">
              <div className="relative rounded-2xl overflow-hidden shadow-2xl border border-white/10 aspect-video bg-slate-900">
                 {/* Using a placeholder video embed */}
                 <iframe 
                  width="100%" 
                  height="100%" 
                  src="https://www.youtube.com/embed/dQw4w9WgXcQ?si=control" 
                  title="XYRA Promotional Video" 
                  frameBorder="0" 
                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
                  referrerPolicy="strict-origin-when-cross-origin" 
                  allowFullScreen
                  className="w-full h-full object-cover opacity-80 group-hover:opacity-100 transition-opacity duration-300"
                 ></iframe>
              </div>
              {/* Decorative Glow behind video */}
              <div className="absolute -inset-4 bg-gradient-to-r from-cyan-500 to-purple-600 rounded-2xl blur-2xl opacity-20 -z-10 group-hover:opacity-40 transition-opacity duration-500"></div>
            </div>
          </div>
        </div>
      </section>

      {/* Process Section */}
      <section className="py-20 relative">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <SectionHeader title="How We Work" subtitle="The XYRA Process" />
          
          <div className="relative max-w-6xl mx-auto pb-12">
            {/* Timeline Line (Centered behind circles) */}
            <div className="hidden md:block absolute top-6 left-0 w-full h-[2px] bg-gradient-to-r from-transparent via-cyan-500/50 to-transparent z-0 shadow-[0_0_10px_rgba(6,182,212,0.5)]"></div>
            
            <div className="grid grid-cols-1 md:grid-cols-4 gap-8 relative z-10">
              {[
                { title: 'Discovery', desc: 'We analyze your business goals and market.' },
                { title: 'Strategy', desc: 'AI-driven planning to identify opportunities.' },
                { title: 'Execution', desc: 'Deploying campaigns with precision.' },
                { title: 'Optimization', desc: 'Continuous monitoring and improvement.' }
              ].map((step, i) => (
                <div key={i} className="text-center group">
                  {/* Step Circle */}
                  <div className="w-12 h-12 mx-auto bg-[#020617] border-2 border-cyan-500 rounded-full flex items-center justify-center text-xl font-bold text-white mb-6 relative z-10 shadow-[0_0_15px_rgba(6,182,212,0.4)] transition-all duration-300 group-hover:scale-110 group-hover:bg-cyan-950/50 group-hover:shadow-[0_0_25px_rgba(6,182,212,0.6)]">
                    {i + 1}
                  </div>
                  
                  {/* Content */}
                  <h4 className="text-xl font-bold text-white mb-2 group-hover:text-cyan-400 transition-colors">{step.title}</h4>
                  <p className="text-gray-400 text-sm leading-relaxed max-w-[200px] mx-auto">{step.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>
    </>
  );
};